GET http://localhost:8080/home/
Accept: application/json

###
# curl --location --request GET 'http://localhost:8080/home'
#--header 'X-API-KEY: eppTecDemo'
GET http://localhost:8080/home
X-API-KEY: eppTecDemo

###


